package frc.robot.subsystems.camera;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import java.util.HashMap;

import org.opencv.core.*;
import org.opencv.core.Core.*;
import org.opencv.features2d.FeatureDetector;
import org.opencv.imgcodecs.Imgcodecs;
import org.opencv.imgproc.*;
import org.opencv.objdetect.*;

/**
* ExMachina class.
*
* <p>An OpenCV pipeline generated by GRIP.
*
* @author GRIP
*/
public class ExMachina {

	//Outputs
	private Mat rgbThresholdOutput = new Mat();
	private Mat maskOutput = new Mat();
	private Mat blurOutput = new Mat();
	private MatOfRect cascadeClassifierOutput = new MatOfRect();

	static {
		System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
	}

	/**
	 * This is the primary method that runs the entire pipeline and updates the outputs.
	 */
	public void process(Mat source0, CascadeClassifier source1) {
		// Step RGB_Threshold0:
		Mat rgbThresholdInput = source0;
		double[] rgbThresholdRed = {68.79496402877697, 255.0};
		double[] rgbThresholdGreen = {55.03597122302158, 255.0};
		double[] rgbThresholdBlue = {0.0, 126.2121212121212};
		rgbThreshold(rgbThresholdInput, rgbThresholdRed, rgbThresholdGreen, rgbThresholdBlue, rgbThresholdOutput);

		// Step Mask0:
		Mat maskInput = source0;
		Mat maskMask = rgbThresholdOutput;
		mask(maskInput, maskMask, maskOutput);

		// Step Blur0:
		Mat blurInput = maskOutput;
		BlurType blurType = BlurType.get("Box Blur");
		double blurRadius = 2.7027027027027044;
		blur(blurInput, blurType, blurRadius, blurOutput);

		// Step Cascade_Classifier0:
		Mat cascadeClassifierImage = blurOutput;
		CascadeClassifier cascadeClassifierClassifier = source1;
		double cascadeClassifierScaleFactor = 1.1;
		int cascadeClassifierMinNeighbors = 3;
		Size cascadeClassifierMinSize = new Size(0, 0);
		Size cascadeClassifierMaxSize = new Size(0, 0);
		cascadeClassifier(cascadeClassifierImage,cascadeClassifierClassifier,cascadeClassifierOutput,
		 cascadeClassifierScaleFactor, cascadeClassifierMinNeighbors, cascadeClassifierMinSize, cascadeClassifierMaxSize);

	}

	/**
	 * This method is a generated getter for the output of a RGB_Threshold.
	 * @return Mat output from RGB_Threshold.
	 */
	public Mat rgbThresholdOutput() {
		return rgbThresholdOutput;
	}

	/**
	 * This method is a generated getter for the output of a Mask.
	 * @return Mat output from Mask.
	 */
	public Mat maskOutput() {
		return maskOutput;
	}

	/**
	 * This method is a generated getter for the output of a Blur.
	 * @return Mat output from Blur.
	 */
	public Mat blurOutput() {
		return blurOutput;
	}

	/**
	 * This method is a generated getter for the output of a Cascade_Classifier.
	 * @return MatOfRect output from Cascade_Classifier.
	 */
	public MatOfRect cascadeClassifierOutput() {
		return cascadeClassifierOutput;
	}


	/**
	 * Segment an image based on color ranges.
	 * @param input The image on which to perform the RGB threshold.
	 * @param red The min and max red.
	 * @param green The min and max green.
	 * @param blue The min and max blue.
	 * @param output The image in which to store the output.
	 */
	private void rgbThreshold(Mat input, double[] red, double[] green, double[] blue,
		Mat out) {
		Imgproc.cvtColor(input, out, Imgproc.COLOR_BGR2RGB);
		Core.inRange(out, new Scalar(red[0], green[0], blue[0]),
			new Scalar(red[1], green[1], blue[1]), out);
	}

	/**
	 * Filter out an area of an image using a binary mask.
	 * @param input The image on which the mask filters.
	 * @param mask The binary image that is used to filter.
	 * @param output The image in which to store the output.
	 */
	private void mask(Mat input, Mat mask, Mat output) {
		mask.convertTo(mask, CvType.CV_8UC1);
		Core.bitwise_xor(output, output, output);
		input.copyTo(output, mask);
	}

	/**
	 * An indication of which type of filter to use for a blur.
	 * Choices are BOX, GAUSSIAN, MEDIAN, and BILATERAL
	 */
	enum BlurType{
		BOX("Box Blur"), GAUSSIAN("Gaussian Blur"), MEDIAN("Median Filter"),
			BILATERAL("Bilateral Filter");

		private final String label;

		BlurType(String label) {
			this.label = label;
		}

		public static BlurType get(String type) {
			if (BILATERAL.label.equals(type)) {
				return BILATERAL;
			}
			else if (GAUSSIAN.label.equals(type)) {
			return GAUSSIAN;
			}
			else if (MEDIAN.label.equals(type)) {
				return MEDIAN;
			}
			else {
				return BOX;
			}
		}

		@Override
		public String toString() {
			return this.label;
		}
	}

	/**
	 * Softens an image using one of several filters.
	 * @param input The image on which to perform the blur.
	 * @param type The blurType to perform.
	 * @param doubleRadius The radius for the blur.
	 * @param output The image in which to store the output.
	 */
	private void blur(Mat input, BlurType type, double doubleRadius,
		Mat output) {
		int radius = (int)(doubleRadius + 0.5);
		int kernelSize;
		switch(type){
			case BOX:
				kernelSize = 2 * radius + 1;
				Imgproc.blur(input, output, new Size(kernelSize, kernelSize));
				break;
			case GAUSSIAN:
				kernelSize = 6 * radius + 1;
				Imgproc.GaussianBlur(input,output, new Size(kernelSize, kernelSize), radius);
				break;
			case MEDIAN:
				kernelSize = 2 * radius + 1;
				Imgproc.medianBlur(input, output, kernelSize);
				break;
			case BILATERAL:
				Imgproc.bilateralFilter(input, output, -1, radius, radius);
				break;
		}
	}

        /**
        * Runs a cascade classifier on an image.
        *
        * @param input          the image to run the classifier on
        * @param classifier     the clasifier to use
        * @param detections     the mat to store the detected regions in
        * @param scaleFactor    the scale factor of each successive downsized image
        * @param minNeighbors   how many neighbors each candidate rectangle should have to retain it
        * @param minSize        the minimum possible object size
        * @param maxSize        the maximum possible object size. If (0, 0), it is assumed to be unbounded
        */
        private void cascadeClassifier(Mat input, CascadeClassifier classifier, MatOfRect detections,
                double scaleFactor, int minNeighbors, Size minSize, Size maxSize) {
            classifier.detectMultiScale(input, detections, scaleFactor, minNeighbors, 0, minSize, maxSize);
        }




}

